# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Service Catalog - Kubernetes
description: >- # this means to ignore newlines until "baseurl:"
  Kubernetes SIG Service Catalog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svc-cat.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: true
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- proposals
- v1

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-youtube
  - jekyll-relative-links

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - install
  - walkthrough
  - cli
  - concepts
  - docs-home # fallthrough, leave this last
