# Default values for Health Check
# Image to use
image: quay.io/kubernetes-service-catalog/healthcheck:v0.1.9
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: Never
