language: generic
notifications:
  email:
    recipients:
      - kubernetes-sig-service-catalog-alerts@googlegroups.com
sudo: required
services:
- docker
cache:
  directories:
    # ${GOPATH}/pkg is mounted in DOCKER_CMD in Makefile
    - .pkg
stages:
  - test
  - name: deploy
    if: type != pull_request
  - name: push-chart
    # require the tag name to match a regular expression
    if: tag =~ ^v
before_install:
  - |
      if [[ -z "$TRAVIS_COMMIT_RANGE" ]]; then
          # Builds triggered by initial commit of a new branch.
          DOCS_ONLY=0
      else
          DOCS_REGEX='(OWNERS|LICENSE)|(\.md$)|(^docs/)|(^docsite/)'
          [[ -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -vE $DOCS_REGEX)" ]]
          DOCS_ONLY=$?
      fi
jobs:
  fast_finish: true
  include:
    # CI Build
    - stage: test
      script:
      - |
        if (( $DOCS_ONLY == 0 )); then
          echo "Running verify-docs"
          make verify-docs
        else
          echo "Running full build"
          make verify build build-integration build-e2e test images svcat-all
          openssl aes-256-cbc -K $encrypted_8471c4fb0720_key -iv $encrypted_8471c4fb0720_iv -in kubernetes-charts-d97457a83e61.json.enc -out kubernetes-charts-d97457a83e61.json -d
        fi
      env: GO_VERSION=1.9
    # Cross Build Check
    - stage: test
      script:
      - |
        if (( $DOCS_ONLY != 0 )); then
          make images-all
        fi
      env: XBUILD=true
    # Doc Site svc-cat.io
    - stage: test
      script: make docs
      env: DOCS=true
    # Deploy
    - stage: deploy
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: contrib/travis/deploy.sh
        on:
          repo: kubernetes-incubator/service-catalog
          all_branches: true
    - stage: push-chart
      script: test/repo-sync.sh
