language: generic
sudo: required
services:
- docker
cache:
  directories:
  - .glide
script:
- make verify build build-integration build-e2e test images
deploy:
  skip_cleanup: true
  provider: script
  script: contrib/travis/deploy.sh
  on:
    repo: kubernetes-incubator/service-catalog
    all_branches: true
