kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: apiserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: {{ .Values.registry }}/apiserver:{{ if .Values.k8sApiServerVersion }}{{ .Values.k8sApiServerVersion }}{{ else }}{{ default "latest" .Values.version }}{{ end }}
        imagePullPolicy: {{ default "Always" .Values.imagePullPolicy }}
        args: 
        - --etcd-servers
        - http://localhost:2379
        - -v
        - "10"
        ports:
        - containerPort: 6443
        volumeMounts:
        - name: apiserver-ssl
          mountPath: /var/run/kubernetes-service-catalog
          readOnly: true
      - name: etcd
        image: {{ if .Values.etcdRepository }}{{ .Values.etcdRepository }}{{ else }}{{ "quay.io/coreos/etcd" }}{{ end }}:{{ if .Values.etcdVersion }}{{ .Values.etcdVersion }}{{ else }}{{ "latest" }}{{ end }}
      volumes:
      - name: apiserver-ssl
        secret:
          secretName: apiserver-ssl
---
kind: Service
apiVersion: v1
metadata:
  name: apiserver
spec:
{{ if .Values.debug }}
  type: LoadBalancer
{{ end }}
  selector:
    app: apiserver
  ports:
  - protocol: TCP
    port: 6443
    targetPort: 6443
