kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: {{ default "catalog" .Values.namespace }}
  name: ups-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ups-broker
    spec:
      containers:
      - name: ups-broker
        image: {{ .Values.registry }}/user-broker:{{ if .Values.upsBrokerVersion }}{{ .Values.upsBrokerVersion }}{{ else }}{{ default "latest" .Values.version }}{{ end }}
        imagePullPolicy: Always
        args:
        - --port
        - "8000"
        ports:
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ default "catalog" .Values.namespace }}
  name: ups-broker
spec:
{{ if .Values.debug }}
  type: LoadBalancer
{{ end }}
  selector:
    app: ups-broker
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
