apiVersion: settings.servicecatalog.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: add-port-env-all
spec:
  selector:
    matchLabels:
      mutateAll: "true"
  env:
    - name: PORT
      value: "1111"
